const SHEET_ID='1rCwSwyrqlW4jn-pfhaL3r1zwal2ZVFui1_0MZM4xuN0';
const SHEET_CSV_URL=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:csv`;
const menuToggle=document.querySelector('.menu-toggle');
const mobileNav=document.querySelector('.mobile-nav');
menuToggle?.addEventListener('click',()=>{const open=mobileNav.classList.toggle('is-open');menuToggle.setAttribute('aria-expanded',String(open));});
document.querySelectorAll('.mobile-nav a').forEach(link=>link.addEventListener('click',()=>{mobileNav.classList.remove('is-open');menuToggle?.setAttribute('aria-expanded','false');}));

const weekLabel=document.querySelector('#week-label');
const filterButtons=document.querySelectorAll('.filter-button');
const scheduleGrid=document.querySelector('#schedule-grid');
const dayNames=['monday','tuesday','wednesday','thursday','friday','saturday','sunday'];
let weekOffset=0;
const weekNames=['Tuần trước / Previous week','Tuần hiện tại / This week','Tuần sau / Next week'];
function updateWeek(){weekLabel.textContent=weekOffset===0?weekNames[1]:weekOffset<0?`${Math.abs(weekOffset)} tuần trước / ${Math.abs(weekOffset)} weeks ago`:`${weekOffset} tuần tới / ${weekOffset} weeks ahead`;}
document.querySelectorAll('[data-week]').forEach(button=>button.addEventListener('click',()=>{const action=button.dataset.week;if(action==='previous')weekOffset--;if(action==='next')weekOffset++;if(action==='today')weekOffset=0;updateWeek();}));

function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'&&quoted&&next==='"'){cell+='"';i++;continue}if(ch==='"'){quoted=!quoted;continue}if(ch===','&&!quoted){row.push(cell);cell='';continue}if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(cell);rows.push(row);row=[];cell='';continue}cell+=ch}if(cell||row.length){row.push(cell);rows.push(row)}return rows.map(r=>r.map(v=>v.trim()));}
function normalize(value){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();}
function classMeta(value){const text=normalize(value);if(text.includes('reformer'))return {type:'reformer',name:'Reformer Pilates Group'};if(text.includes('wallunit')||text.includes('wall unit'))return {type:'wall-unit',name:'Wall unit Pilates Group'};if(text.includes('mat'))return {type:'mat',name:'Mat Pilates Group'};return null;}
function formatTime(value){return value.replace(/(\d{1,2})h/ig,'$1:00').replace(/\s*-\s*/,' — ').replace(/\s+/g,' ').trim();}
function dayKey(value){const text=normalize(value);if(text.includes('chu nhat')||text.includes('sun'))return 'sunday';const numeric=text.match(/(?:^|\s)([2-7])(?:\s|$)/);if(numeric)return dayNames[Number(numeric[1])-2];if(text.includes('mon'))return 'monday';if(text.includes('tue'))return 'tuesday';if(text.includes('wed'))return 'wednesday';if(text.includes('thu'))return 'thursday';if(text.includes('fri'))return 'friday';if(text.includes('sat'))return 'saturday';return null;}
function bookingLink(){return '../?session=group#booking';}
function createCard(time,value){const meta=classMeta(value);if(!meta)return null;const card=document.createElement('div');card.className='class-card';card.dataset.type=meta.type;card.innerHTML=`<time>${formatTime(time)}</time><h3>${meta.name}</h3><p>Lớp nhóm / Group class</p><small>Tối đa 4 người / Max 4 people</small><a href="${bookingLink()}" class="class-book">Đặt tập thử / Book trial</a>`;return card;}
function renderFromSheet(rows){const headerIndex=rows.findIndex(row=>normalize(row[0]||'').includes('khung gio'));if(headerIndex<0)throw new Error('Không tìm thấy hàng KHUNG GIỜ / KHUNG GIỜ row not found');const headers=rows[headerIndex];const columns=headers.map(dayKey);const grid=document.querySelector('#schedule-grid');grid.innerHTML='';const columnsByDay={};dayNames.forEach(day=>{const column=document.createElement('article');column.className='day-column';column.dataset.day=day;column.innerHTML=`<header><span></span><b></b></header><div class="class-stack"></div>`;columnsByDay[day]=column;grid.appendChild(column);});for(let i=0;i<columns.length;i++){const key=columns[i];if(key&&columnsByDay[key]){const header=headers[i].split('\n');columnsByDay[key].querySelector('header span').textContent=header[0]||key.toUpperCase();columnsByDay[key].querySelector('header b').textContent=header[1]||key.slice(0,3).toUpperCase();}}
rows.slice(headerIndex+1).forEach(row=>{const time=row[0];if(!time||!/[0-9]/.test(time))return;row.forEach((value,index)=>{const key=columns[index];if(!key||!columnsByDay[key]||!value)return;const card=createCard(time,value);if(card)columnsByDay[key].querySelector('.class-stack').appendChild(card);});});dayNames.forEach(day=>{const column=columnsByDay[day];if(!column.querySelector('.class-card'))column.remove();});const title=rows[1]?.[0]||'';const match=title.match(/(\d{1,2}\/\d{1,2}\s*-\s*\d{1,2}\/\d{1,2})/);if(match)weekLabel.textContent=`${match[1]} / This week`;applyFilter('all');}
function removeEmptyDays(){document.querySelectorAll('.day-column').forEach(day=>{if(!day.querySelector('.class-card'))day.remove();});}
function applyFilter(filter){filterButtons.forEach(item=>item.classList.toggle('is-active',item.dataset.filter===filter));document.querySelectorAll('.class-card').forEach(card=>{card.hidden=filter!=='all'&&!card.dataset.type.split(' ').includes(filter);});document.querySelectorAll('.day-column').forEach(day=>{const hasVisible=Boolean(day.querySelector('.class-card:not([hidden])'));day.hidden=!hasVisible;day.classList.toggle('is-empty',!hasVisible);});}
filterButtons.forEach(button=>button.addEventListener('click',()=>applyFilter(button.dataset.filter)));
async function loadSheet(){if(!scheduleGrid)return;const status=document.querySelector('#sheet-status');try{const response=await fetch(`${SHEET_CSV_URL}&_=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const rows=parseCsv(await response.text());renderFromSheet(rows);scheduleGrid.classList.remove('is-loading');if(status){status.textContent='Đã cập nhật từ Google Sheets / Updated from Google Sheets';status.classList.add('is-live');}}catch(error){console.warn('Google Sheets unavailable; using the built-in fallback schedule.',error);scheduleGrid.classList.remove('is-loading');if(status){status.textContent='Đang hiển thị lịch dự phòng / Showing fallback schedule';status.classList.add('is-fallback');}removeEmptyDays();const cards=[...document.querySelectorAll('.class-card')];cards.forEach(card=>card.dataset.type=card.dataset.type||'mat');applyFilter('all');}}
if(scheduleGrid)loadSheet();
